name: Docker

on:
  workflow_call:

jobs:
  docker:
    name: Test on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up docker build
      uses: docker/setup-buildx-action@v3.3.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: app_go
    
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ferreiradavid
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags:  ferreiradavid/go_ci:${{ github.ref_name }}          
